-- ============================================================
-- EMCALI MOP — Datos Iniciales (Seed)
-- ============================================================

-- ── ROLES ───────────────────────────────────────────────────
INSERT INTO roles (nombre) VALUES
    ('administrador'),
    ('gestor'),
    ('consulta')
ON CONFLICT DO NOTHING;

-- ── USUARIO ADMIN INICIAL ────────────────────────────────────
-- Password: Admin2025! (hash bcrypt generado por el backend al inicializar)
-- Se crea vía endpoint /api/auth/init-admin en el primer arranque

-- ── MACROPROCESOS ────────────────────────────────────────────
INSERT INTO macroprocesos (codigo, nombre, descripcion, color_hex, orden) VALUES
('MP01','Planeación y Evaluación Estratégica','Direcciona la estrategia corporativa, gestiona el banco de proyectos, la calidad, la regulación y los controles institucionales.','#1A237E',1),
('MP02','Acueducto y Saneamiento Básico','Opera el ciclo integral del agua: captación, potabilización, distribución, recolección y tratamiento de aguas residuales.','#004D40',2),
('MP03','Servicios Energéticos','Gestiona la distribución del SDL, la compra de energía en el MEM y la comercialización al mercado regulado y no regulado.','#BF360C',3),
('MP04','Servicios TIC','Provee servicios de fibra óptica, internet, telefonía y televisión en segmentos B2C, B2B y B2G.','#4A148C',4),
('MP05','Soporte Corporativo','Habilita los negocios mediante gestión del talento, finanzas, abastecimiento, jurídica y tecnología corporativa.','#1B5E20',5)
ON CONFLICT (codigo) DO NOTHING;

-- ── PROCESOS MP01 ────────────────────────────────────────────
INSERT INTO procesos (macroproceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
((SELECT id FROM macroprocesos WHERE codigo='MP01'),'P0101','Direccionamiento Corporativo','INICIA: Análisis del entorno y directrices JD. INCLUYE: PEC, banco de proyectos, CMI, alianzas. TERMINA: PEC aprobado y comunicado.','% Cumplimiento PEC (≥85%)\n% Proyectos con evaluación financiera (≥80%)','Subgerente de Planeación y Desarrollo Empresarial',1),
((SELECT id FROM macroprocesos WHERE codigo='MP01'),'P0102','Planeación, Calidad y Regulación','INICIA: Política de calidad y marcos regulatorios. INCLUYE: SGI, auditorías, regulación CRA/CREG/CRC, innovación. TERMINA: SGI certificado.','% Certificaciones SGI vigentes (100%)\n% Respuestas regulatorias en plazo (100%)','Subgerente de Planeación y Desarrollo Empresarial',2),
((SELECT id FROM macroprocesos WHERE codigo='MP01'),'P0103','Sostenibilidad y RSA','INICIA: Política ambiental y social. INCLUYE: Programas ambientales, RSA, permisos, ESG. TERMINA: Informes de sostenibilidad publicados.','% Programas ambientales ejecutados (≥90%)\nConcesiones vigentes (100%)','Subgerente de Planeación',3),
((SELECT id FROM macroprocesos WHERE codigo='MP01'),'P0104','Controles Institucionales','INICIA: Plan de auditorías y mapa de riesgos. INCLUYE: Auditorías, control interno, MIPG, anticorrupción. TERMINA: Informes presentados a JD.','Índice desempeño MIPG (≥70%)\n% Hallazgos con plan de mejora (≥90%)','Jefe Control Interno',4)
ON CONFLICT (codigo) DO NOTHING;

-- ── PROCESOS MP02 ────────────────────────────────────────────
INSERT INTO procesos (macroproceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
((SELECT id FROM macroprocesos WHERE codigo='MP02'),'P0201','Planeación, Prospectiva y Evaluación del Negocio A&A','INICIA: Análisis del entorno del negocio. INCLUYE: Plan Maestro A&A, POIR, banco proyectos, proyecciones financieras. TERMINA: Informe de gestión.','% Ejecución Plan Maestro A&A (≥90%)\n% Proyectos A&A con evaluación financiera (≥80%)','Gerente GUENAA',1),
((SELECT id FROM macroprocesos WHERE codigo='MP02'),'P0202A','Captación, Potabilización y Distribución de Agua','INICIA: Captación agua cruda en bocatomas. INCLUYE: Potabilización PTAP, almacenamiento, distribución. TERMINA: Suministro de agua potable al usuario.','IRCA mensual (Sin Riesgo <5%)\nContinuidad servicio (≥20 h/día)\nIANC (≤30%)','Subgerente de Operaciones GUENAA',2),
((SELECT id FROM macroprocesos WHERE codigo='MP02'),'P0202B','Recolección, Tratamiento y Disposición de AR','INICIA: Recolección de AR. INCLUYE: Red alcantarillado, bombeo, PTAR-C. TERMINA: Vertimiento conforme PSMV.','Eficiencia remoción DBO5 (≥80%)\nConformidad vertimiento PSMV (100%)','Subgerente de Operaciones GUENAA',3),
((SELECT id FROM macroprocesos WHERE codigo='MP02'),'P0203','Garantía de Calidad, Control de Pérdidas y Comercial A&A','INICIA: Análisis de calidad del agua y balance hídrico. INCLUYE: Laboratorio, IANC, comercialización, PQR. TERMINA: Ingresos facturados y usuarios satisfechos.','IANC (≤30%)\nEficiencia recaudo A&A (≥92%)\nNSU A&A (≥80)','Gerente GUENAA',4)
ON CONFLICT (codigo) DO NOTHING;

-- ── PROCESOS MP03 ────────────────────────────────────────────
INSERT INTO procesos (macroproceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0301','Planeación Negocio Energía','INICIA: Análisis de la demanda y regulación CREG. INCLUYE: Plan Inversión SDL, EBIE, banco proyectos. TERMINA: Plan aprobado e inscrito.','% Ejecución Plan Inversión SDL (≥90%)','Gerente GUENE',1),
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0302A','Distribución y Operación del SDL','INICIA: Recepción de energía en puntos de frontera. INCLUYE: Operación subestaciones, mantenimiento redes, expansión SDL. TERMINA: Energía entregada al usuario.','SAIDI y SAIFI (conforme OM CREG)\nDisponibilidad SDL (≥99.5%)','Subgerente de Operaciones GUENE',2),
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0302B','Gestión de Pérdidas de Energía','INICIA: Balance de energía comprada vs. facturada. INCLUYE: Detección fraude, control fronteras comerciales. TERMINA: kWh recuperados y facturados.','Índice pérdidas totales (≤12%)\nkWh recuperados/mes','Subgerente de Operaciones GUENE',3),
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0302C','Gestión Alumbrado Público (SALP)','INICIA: Contrato de administración AP con la Alcaldía. INCLUYE: Operación, mantenimiento, expansión AP. TERMINA: Informe de gestión y facturación SALP.','Disponibilidad SALP (≥95%)\nFacturación AP al municipio ($)','Gerente GUENE',4),
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0303A','Compra de Energía en el MEM','INICIA: Pronóstico de demanda y análisis del mercado. INCLUYE: Contratos bilaterales, bolsa de energía, ASIC. TERMINA: Contratos registrados.','Costo unitario compra ($/kWh) vs. precio bolsa\n% cobertura contratos (≥70%)','Subgerente Comercial GUENE',5),
((SELECT id FROM macroprocesos WHERE codigo='MP03'),'P0303B','Comercialización y Venta de Energía (MR y MNR)','INICIA: Facturación al MR y contratos MNR. INCLUYE: Facturación MR, gestión MNR, recaudo, PQR. TERMINA: Ingresos recaudados y usuarios satisfechos.','Eficiencia recaudo energía (≥95%)\nNSU energía (≥80)','Subgerente Comercial GUENE',6)
ON CONFLICT (codigo) DO NOTHING;

-- ── PROCESOS MP04 ────────────────────────────────────────────
INSERT INTO procesos (macroproceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
((SELECT id FROM macroprocesos WHERE codigo='MP04'),'P0401','Estrategia de la Prestación del Servicio TIC','INICIA: Análisis del mercado TIC y lineamientos corporativos. INCLUYE: Plan estratégico UENTIC, portafolio, regulación CRC. TERMINA: Plan aprobado.','% Cumplimiento obligaciones MinTIC (100%)\n% Proyectos TIC en banco integrado (100%)','Gerente GUENTIC',1),
((SELECT id FROM macroprocesos WHERE codigo='MP04'),'P0402B','Diseño e Implementación de Proyectos de Red TIC','INICIA: Plan de expansión de red aprobado. INCLUYE: Ingeniería, obras civiles, instalación equipos activos. TERMINA: Activos activados en operación.','% Proyectos red en fecha (≥85%)\nkm fibra tendida vs. plan','Subgerente de Red GUENTIC',2),
((SELECT id FROM macroprocesos WHERE codigo='MP04'),'P0403','Operación y Mantenimiento de Servicios TIC','INICIA: Monitoreo continuo desde el NOC. INCLUYE: Operación servicios, seguridad informática, gestión incidencias. TERMINA: Disponibilidad conforme ANS.','Disponibilidad TIC (≥99.5%)\nMTRS (≤4h)','Subgerente de Operaciones GUENTIC',3),
((SELECT id FROM macroprocesos WHERE codigo='MP04'),'P0404','Gestión de Promesa de Valor y Venta de Servicios TIC','INICIA: Plan de mercadeo y ventas por segmento. INCLUYE: Mercadeo, ventas B2C/B2B/B2G, facturación, retención. TERMINA: Ingresos TIC recaudados.','Ingresos TIC crecimiento anual (≥+8%)\nChurn B2C (≤2%)','Subgerente Comercial GUENTIC',4)
ON CONFLICT (codigo) DO NOTHING;

-- ── PROCESOS MP05 ────────────────────────────────────────────
INSERT INTO procesos (macroproceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
((SELECT id FROM macroprocesos WHERE codigo='MP05'),'P0501','Gestión del Talento Humano','INICIA: Planeación necesidades de talento por negocio. INCLUYE: Vinculación, nómina, formación, SST, bienestar. TERMINA: Personal competente disponible.','Cobertura cargos críticos (≥90%)\nRotación no deseada (≤5%)','Gerente de Gestión Humana',1),
((SELECT id FROM macroprocesos WHERE codigo='MP05'),'P0502','Gestión Financiera y Contable','INICIA: Definición del plan de cuentas regulatorio y presupuesto. INCLUYE: Contabilidad regulatoria CRA/CREG/CRC, EEFF por negocio. TERMINA: EEFF presentados.','EBITDA por negocio (positivo)\n% costos asignados en SAP (≥95%)','Subgerente Financiero',2),
((SELECT id FROM macroprocesos WHERE codigo='MP05'),'P0503','Gestión de Compras, Contratos y Suministros','INICIA: Consolidación del PACC. INCLUYE: Planeación, selección, contratación, supervisión. TERMINA: Contratos ejecutados y bienes entregados.','% PAC ejecutado en fecha (≥85%)\nAhorro en procesos competitivos (≥5%)','Subgerente de Abastecimiento',3),
((SELECT id FROM macroprocesos WHERE codigo='MP05'),'P0504','Gestión Jurídica y Legal','INICIA: Solicitud de asesoría jurídica o notificación de proceso legal. INCLUYE: Asesoría contractual, defensa judicial, gestión siniestros. TERMINA: Contratos legalizados.','% procesos judiciales con fallo favorable (≥65%)\n% contratos revisados en plazo (100%)','Secretaría General / Jefe Jurídico',4),
((SELECT id FROM macroprocesos WHERE codigo='MP05'),'P0505','Gestión de TI Corporativa','INICIA: Requerimientos de negocios y políticas de seguridad. INCLUYE: ERP, SCADA, GIS, CRM, ciberseguridad, continuidad. TERMINA: Sistemas disponibles.','Disponibilidad sistemas misionales (≥99%)\n% incidentes de seguridad mitigados (100%)','Jefe TI Corporativo',5)
ON CONFLICT (codigo) DO NOTHING;

-- ── SUBPROCESOS (representativos por proceso) ────────────────
INSERT INTO subprocesos (proceso_id, codigo, descripcion, alcance, indicador, responsable, orden) VALUES
-- MP01
((SELECT id FROM procesos WHERE codigo='P0101'),'SP010101','Gestión Estratégica y Banco de Proyectos Corporativo','INICIA: Prospectiva y lineamientos JD. INCLUYE: PEC, banco proyectos, proyecciones 5 años, CMI. TERMINA: Informe anual de rendición de cuentas.','Cumplimiento CMI trimestral (%)\n% proyectos con evaluación financiera','Jefe Unidad Prospectiva Estratégica',1),
((SELECT id FROM procesos WHERE codigo='P0101'),'SP010102','Comunicación Empresarial','INICIA: Lineamientos de comunicación de la alta dirección. INCLUYE: Comunicación interna, externa, relaciones públicas. TERMINA: Informe de impacto.','Alcance de campañas (%)\nSatisfacción comunicación interna (≥75%)','Jefe Oficina de Comunicaciones',2),
((SELECT id FROM procesos WHERE codigo='P0102'),'SP010201','Gestión de Calidad e Integración SGI','INICIA: Política y objetivos de calidad. INCLUYE: Auditorías, no conformidades, revisión por la dirección. TERMINA: Informe de revisión.','% Certificaciones SGI vigentes (100%)\n% NC cerradas en plazo (≥90%)','Jefe Unidad Gestión de la Calidad',1),
((SELECT id FROM procesos WHERE codigo='P0102'),'SP010202','Gestión de Regulación Empresarial (CRA/CREG/CRC)','INICIA: Expedición de normas por entes reguladores. INCLUYE: Análisis impactos, implementación, reportes de cumplimiento. TERMINA: Informes de cumplimiento.','% respuestas regulatorias en plazo (100%)\nN° sanciones regulatorias (meta: 0)','Jefe Unidad Regulación Empresarial',2),
((SELECT id FROM procesos WHERE codigo='P0102'),'SP010203','Desarrollo de Nuevos Negocios e Innovación','INICIA: Vigilancia tecnológica y análisis de tendencias. INCLUYE: Estructuración, validación, puesta en marcha. TERMINA: Nuevo negocio operativo.','N° nuevos negocios lanzados/año (≥1)\nPortafolio actualizado semestralmente','Jefe Unidad Desarrollo de Negocios',3),
((SELECT id FROM procesos WHERE codigo='P0103'),'SP010301','Gestión Ambiental Empresarial','INICIA: Política ambiental y compromisos regulatorios. INCLUYE: PSMV, PGIRS, PUEAA, permisos y concesiones. TERMINA: Informes de cumplimiento ambiental.','% programas ambientales ejecutados (≥90%)\nConcesiones y permisos vigentes (100%)','Jefe Ambiental',1),
((SELECT id FROM procesos WHERE codigo='P0104'),'SP010401','Control Interno y Auditoría','INICIA: Plan anual de auditorías y mapa de riesgos. INCLUYE: Auditorías internas, seguimiento MIPG, evaluaciones. TERMINA: Informes presentados a JD.','Índice desempeño MIPG (≥70%)\n% hallazgos con plan de mejora','Jefe Control Interno',1),
-- MP02
((SELECT id FROM procesos WHERE codigo='P0201'),'SP020101','Planeación Estratégica del Negocio A&A','INICIA: Análisis de contexto del sector A&A. INCLUYE: PUEAA, planes de expansión, metas regulatorias, banco de proyectos. TERMINA: Plan aprobado.','% ejecución Plan Maestro A&A\n% proyectos A&A en banco integrado (100%)','Jefe Planeación A&A',1),
((SELECT id FROM procesos WHERE codigo='P0202A'),'SP020201','Producción de Agua Potable (Captación + PTAP)','INICIA: Operación de bocatomas y sistemas de aducción. INCLUYE: Coagulación, floculación, sedimentación, filtración, desinfección. TERMINA: Agua conforme IRCA.','IRCA mensual (Sin Riesgo <5%)\nm³ producidos por turno','Jefe Plantas de Potabilización',1),
((SELECT id FROM procesos WHERE codigo='P0202A'),'SP020204','Distribución en Red de Acueducto','INICIA: Recepción de agua en la red primaria. INCLUYE: Operación redes, sectorización, bombeo, macromedición. TERMINA: Servicio entregado al usuario.','Continuidad servicio (≥20 h/día)\nPresión en red (dentro de norma CRA)','Jefe de Red de Distribución A&A',2),
((SELECT id FROM procesos WHERE codigo='P0202B'),'SP020202','Tratamiento de Aguas Residuales (PTAR-C)','INICIA: Recepción de AR en el sistema de cribado. INCLUYE: Tratamiento primario, secundario, digestión de lodos, biosólidos. TERMINA: Efluente conforme PSMV.','Eficiencia remoción DBO5 (≥80%)\nConformidad vertimiento PSMV (100%)','Jefe PTAR-C',1),
((SELECT id FROM procesos WHERE codigo='P0203'),'SP020302','Control de Pérdidas A&A (IANC)','INICIA: Balance hídrico mensual del sistema. INCLUYE: Sectorización, detección de fugas, control de fraudes. TERMINA: Informe IANC y plan de reducción.','IANC mensual (≤30%)\nkm red sectorizada (%)','Jefe Control de Pérdidas A&A',1),
((SELECT id FROM procesos WHERE codigo='P0203'),'SP020303','Comercialización y Aseguramiento de Ingresos A&A','INICIA: Lectura de medidores y generación de facturas. INCLUYE: Facturación, recaudo, vinculación, PQR, cartera. TERMINA: Ingresos recaudados.','Eficiencia recaudo A&A (≥92%)\nNSU A&A (≥80)','Jefe Comercial A&A',2),
-- MP03
((SELECT id FROM procesos WHERE codigo='P0301'),'SP030101','Planeación Estratégica y Técnica Negocio Energía','INICIA: Análisis del entorno regulatorio CREG. INCLUYE: Plan estratégico GUENE, plan inversión SDL, EBIE. TERMINA: Plan aprobado e inscrito.','% proyectos energía en banco integrado (100%)\n% ejecución plan inversión SDL','Jefe Planeación GUENE',1),
((SELECT id FROM procesos WHERE codigo='P0302A'),'SP030201','Operación del Sistema Eléctrico SDL','INICIA: Recepción energía en puntos de frontera. INCLUYE: Monitoreo SCADA, telemando, despacho, contingencias. TERMINA: Informe diario operación.','Disponibilidad Centro de Control (≥99.9%)\nTiempo respuesta contingencias (≤30 min)','Jefe Centro de Control GUENE',1),
((SELECT id FROM procesos WHERE codigo='P0302A'),'SP030202','Mantenimiento del SDL','INICIA: Plan de mantenimiento preventivo del SDL. INCLUYE: Mantenimiento subestaciones, redes MT/BT, transformadores. TERMINA: SDL disponible.','% mantenimientos preventivos ejecutados (≥90%)\nMTBF SDL (benchmark CREG)','Jefe de Mantenimiento GUENE',2),
((SELECT id FROM procesos WHERE codigo='P0302B'),'SP030206','Programa de Reducción de Pérdidas de Energía','INICIA: Balance de energía y sectores críticos. INCLUYE: Detección fraude, reconexiones ilegales, mejoras medición. TERMINA: kWh recuperados.','Índice pérdidas totales (≤12%)\nkWh recuperados y facturados/mes','Jefe Control de Pérdidas GUENE',1),
((SELECT id FROM procesos WHERE codigo='P0302C'),'SP030204','Gestión Operativa del SALP','INICIA: Contrato de administración AP con la Alcaldía. INCLUYE: Operación, mantenimiento luminarias, expansión, facturación. TERMINA: SALP disponible.','Disponibilidad SALP (≥95%)\nFacturación AP al municipio ($)','Jefe SALP',1),
((SELECT id FROM procesos WHERE codigo='P0303A'),'SP030302','Compra de Energía en el Mercado Mayorista (MEM)','INICIA: Pronóstico de demanda y análisis del mercado. INCLUYE: Estrategia de compra, contratos bilaterales, bolsa, ASIC. TERMINA: Contratos registrados.','Costo unitario compra ($/kWh) vs. precio bolsa\n% cobertura contratos (≥70%)','Jefe Compra de Energía GUENE',1),
((SELECT id FROM procesos WHERE codigo='P0303B'),'SP030303','Comercialización y Venta de Energía (MR y MNR)','INICIA: Facturación al MR y emisión de contratos MNR. INCLUYE: Facturación MR, gestión MNR, recaudo, PQR. TERMINA: Ingresos recaudados.','Eficiencia recaudo energía (≥95%)\nNSU energía (≥80)','Jefe Comercial GUENE',1),
-- MP04
((SELECT id FROM procesos WHERE codigo='P0401'),'SP040101','Planeación Estratégica y Financiera TIC','INICIA: Análisis de mercado y lineamientos PEC. INCLUYE: Plan estratégico UENTIC, BEP TIC, proyecciones. TERMINA: Plan aprobado.','% proyectos TIC en banco integrado (100%)\nBEP TIC con evaluación financiera (≥80%)','Jefe Planeación GUENTIC',1),
((SELECT id FROM procesos WHERE codigo='P0402B'),'SP040202','Implementación de Proyectos de Red e Infraestructura TIC','INICIA: Plan de expansión de red aprobado. INCLUYE: Diseño ingeniería, obras civiles, instalación equipos. TERMINA: Activos activados.','% proyectos red en fecha (≥85%)\nkm fibra tendida vs. plan','Jefe Proyectos Red TIC',1),
((SELECT id FROM procesos WHERE codigo='P0403'),'SP040301','Operación de Plataformas TIC (NOC)','INICIA: Monitoreo continuo 24/7. INCLUYE: Gestión incidencias, operación servicios voz/datos/TV. TERMINA: ANS conformes.','Disponibilidad servicios (≥99.5%)\nMTRS (≤4h)','Jefe NOC TIC',1),
((SELECT id FROM procesos WHERE codigo='P0404'),'SP040404','Gestión Comercial TIC (B2C/B2B/B2G)','INICIA: Plan de ventas y mercadeo por segmento. INCLUYE: Prospección, venta, facturación, retención, cartera. TERMINA: Contratos activos e ingresos recaudados.','Ingresos TIC por segmento ($)\nChurn B2C (≤2%)','Jefe Comercial GUENTIC',1),
-- MP05
((SELECT id FROM procesos WHERE codigo='P0501'),'SP050101','Planeación y Gestión del Talento Humano','INICIA: Análisis necesidades de personal por negocio. INCLUYE: Planta de personal, vinculación, nómina, convención colectiva. TERMINA: Personal disponible.','N° vacantes críticas sin cubrir\nNómina liquidada correctamente (100%)','Jefe de Talento Humano',1),
((SELECT id FROM procesos WHERE codigo='P0501'),'SP050102','Gestión del Conocimiento y Relevo Generacional','INICIA: Identificación de cargos críticos con riesgo de jubilación. INCLUYE: Documentación conocimiento tácito, banco de conocimiento, mentoring. TERMINA: Conocimiento crítico documentado.','% procesos críticos documentados (≥80%)\nN° programas de mentoring activos (≥50)','Jefe TH + Jefes GUENs',2),
((SELECT id FROM procesos WHERE codigo='P0502'),'SP050201','Contabilidad General y Regulatoria (CRA/CREG/CRC)','INICIA: Creación de centros de costo regulatorios en SAP. INCLUYE: Contabilidad regulatoria, EEFF por negocio, costos ABC. TERMINA: EEFF regulatorios presentados.','% costos asignados a eslabón regulatorio (≥95%)\nEEFF por negocio en plazo (100%)','Jefe de Contabilidad',1),
((SELECT id FROM procesos WHERE codigo='P0503'),'SP050301','Planeación y Control del Abastecimiento','INICIA: Recopilación de necesidades de contratación de los 3 negocios. INCLUYE: PACC consolidado, políticas de contratación. TERMINA: PACC aprobado.','% PACC ejecutado (≥85%)\nAhorro en procesos competitivos (≥5%)','Jefe de Abastecimiento',1),
((SELECT id FROM procesos WHERE codigo='P0504'),'SP050401','Gestión Jurídica y Contractual','INICIA: Solicitud de revisión jurídica de un contrato. INCLUYE: Revisión contratos, conceptos jurídicos, defensa judicial. TERMINA: Contratos legalizados.','% contratos revisados en plazo (100%)\n% procesos con fallo favorable (≥65%)','Jefe Jurídico',1),
((SELECT id FROM procesos WHERE codigo='P0505'),'SP050501','Infraestructura TI Corporativa y Ciberseguridad','INICIA: Necesidades tecnológicas de los negocios. INCLUYE: Gestión ERP/SAP, SCADA, GIS, CRM, ciberseguridad. TERMINA: Sistemas disponibles y seguros.','Disponibilidad sistemas misionales (≥99%)\n% incidentes seguridad mitigados (100%)','Jefe Infraestructura TI',1)
ON CONFLICT (codigo) DO NOTHING;

-- ── ACTIVIDADES (39 actividades) ─────────────────────────────

-- MP01 – 9 actividades
INSERT INTO actividades (subproceso_id, codigo, descripcion, alcance, indicador, responsable, producto, habilitador_negocio, es_critica, nota_critica, orden) VALUES

((SELECT id FROM subprocesos WHERE codigo='SP010101'),'A010101003','Realizar Direccionamiento, Implantación y Seguimiento de la Estrategia','INICIA: Prospectiva y análisis del entorno. INCLUYE: Mapa estratégico, CMI corporativo, planes de negocio articulados, proyecciones 5 años. TERMINA: PEC aprobado y comunicado.','% Objetivos estratégicos con meta cumplida\nCumplimiento PEC semestral','Jefe Unidad Prospectiva Estratégica','Plan Estratégico Corporativo (PEC) vigente\nMapa estratégico y CMI\nProyecciones financieras 5 años','Orienta el banco de proyectos de GUENAA (expansión A&A), GUENE (Plan SDL, EBIE) y GUENTIC (expansión red TIC).',FALSE,NULL,1),

((SELECT id FROM subprocesos WHERE codigo='SP010101'),'A010101347','Planear y Evaluar la Gestión del Portafolio Corporativo','INICIA: Priorización estratégica del portafolio. INCLUYE: Lineamientos PMO, banco proyectos articulado con PFP, aprobación portafolio. TERMINA: Portafolio aprobado y presupuestado.','% PAC derivado de BEP integrado (≥95%)\n% proyectos con ficha completa (100%)','Jefe Unidad Prospectiva Estratégica','Plan del portafolio de proyectos\nBanco de Proyectos integrado con PFP','Cada proyecto del BEP de GUENAA, GUENE y GUENTIC debe estar inscrito y priorizado para garantizar financiamiento y ejecución.',FALSE,NULL,2),

((SELECT id FROM subprocesos WHERE codigo='SP010101'),'A010101341','Gestionar la Administración de Riesgos Empresariales','INICIA: Identificación de riesgos por proceso. INCLUYE: Mapa de riesgos corporativo, controles y seguimiento trimestral. TERMINA: Informe consolidado de riesgos.','% riesgos corporativos con plan de tratamiento (100%)\nMatriz riesgos actualizada trimestralmente','Jefe Unidad Prospectiva','Mapa de riesgos corporativo\nPlan de tratamiento de riesgos\nInforme trimestral de seguimiento','Vincula riesgos de los 3 negocios: desabastecimiento hídrico (A&A), falla SDL (Energía), ciberseguridad (TIC).',FALSE,NULL,3),

((SELECT id FROM subprocesos WHERE codigo='SP010102'),'A010102009','Planear y Evaluar la Comunicación Empresarial','INICIA: Lineamientos de comunicación interna y externa. INCLUYE: Plan de comunicación, política, metodologías de evaluación. TERMINA: Plan aprobado y acciones implementadas.','% Cumplimiento Plan de Comunicación\nÍndice satisfacción comunicación interna','Jefe Comunicaciones','Plan Estratégico de Comunicación\nPolítica de Comunicación\nIndicadores de impacto','Transversal a los 3 negocios: comunica logros de A&A (calidad del agua), Energía (calidad del servicio) y TIC (nuevos servicios) a usuarios y grupos de interés.',FALSE,NULL,4),

((SELECT id FROM subprocesos WHERE codigo='SP010201'),'A010201014','Planear y Evaluar el Sistema de Gestión de Calidad','INICIA: Requisitos normativos ISO 9001. INCLUYE: Plan anual de calidad, indicadores, programación de auditorías. TERMINA: Plan aprobado por la dirección.','Nivel de madurez SGI (≥3/5)\nPlan de calidad aprobado antes del 31 de enero','Jefe SGI / Calidad','Plan anual de calidad\nObjetivos de calidad por negocio\nProgramación de auditorías','Los objetivos de calidad aplican a procesos de GUENAA (IRCA, continuidad), GUENE (SAIDI/SAIFI) y GUENTIC (disponibilidad servicios).',FALSE,NULL,5),

((SELECT id FROM subprocesos WHERE codigo='SP010201'),'A010201292','Gestionar Auditorías Internas y Externas','INICIA: Programación de auditorías internas y externas. INCLUYE: Preparación, acompañamiento y seguimiento post-auditoría. TERMINA: Hallazgos cerrados y certificaciones renovadas.','% Hallazgos auditados con plan de mejora (100%)\nCertificaciones renovadas en plazo','Jefe SGI / Calidad','Certificados de calidad vigentes\nPlanes de mejora cerrados','Verifica el cumplimiento del SGI en procesos de A&A (calidad agua), Energía (operación SDL) y TIC (disponibilidad servicios).',FALSE,NULL,6),

((SELECT id FROM subprocesos WHERE codigo='SP010202'),'A010202260','Implementar y Aplicar Marcos Normativos y Regulatorios','INICIA: Plan de implementación regulatoria aprobado. INCLUYE: Coordinación con GUENs, actualización de tarifas, adaptación de procesos. TERMINA: Cumplimiento verificado y reportado.','% resoluciones regulatorias implementadas por negocio (100%)\nTarifas actualizadas en plazo','Jefe Regulación Empresarial','Resoluciones regulatorias implementadas\nTarifas actualizadas\nReportes CRA / CREG / CRC','Habilita la defensa tarifaria: A&A (tarifas CRA), Energía (cargos CREG OR/STR), TIC (obligaciones CRC/MinTIC).',FALSE,NULL,7),

((SELECT id FROM subprocesos WHERE codigo='SP010203'),'A010203346','Realizar Inteligencia Competitiva y Vigilancia Tecnológica','INICIA: Definición del radar de vigilancia tecnológica. INCLUYE: Recolección, análisis y comunicación de información estratégica. TERMINA: Informe de inteligencia competitiva publicado.','N° informes de inteligencia competitiva/año (≥4)\nOportunidades identificadas por negocio','Jefe Nuevos Negocios','Informe de inteligencia competitiva\nRadar de tendencias tecnológicas','Identifica oportunidades para A&A (soluciones de agua no reguladas), Energía (microrredes, eficiencia energética) y TIC (servicios cloud, IoT).',FALSE,NULL,8),

((SELECT id FROM subprocesos WHERE codigo='SP010301'),'A010301015','Implementar Programas y Proyectos Ambientales','INICIA: Compromisos del PSMV, PGIRS y permisos de concesión. INCLUYE: Ejecución programas ambientales, gestión de vertimientos, residuos, emisiones. TERMINA: Informes ambientales publicados.','% cumplimiento PSMV\n% compromisos ambientales ejecutados en plazo','Jefe Ambiental','Programas ambientales ejecutados\nInformes de seguimiento ambiental','Sin permisos ambientales vigentes los negocios no pueden operar: concesión agua Río Cauca (A&A), gestión residuos SDL (Energía), residuos electrónicos (TIC).',FALSE,NULL,9)

ON CONFLICT (codigo) DO NOTHING;

-- MP02 – 12 actividades
INSERT INTO actividades (subproceso_id, codigo, descripcion, alcance, indicador, responsable, producto, habilitador_negocio, es_critica, nota_critica, orden) VALUES

((SELECT id FROM subprocesos WHERE codigo='SP020101'),'A020101022','Analizar Comportamiento Integral del Servicio A&A','INICIA: Recopilación de indicadores del período. INCLUYE: Análisis IANC, IRCA, continuidad, recaudo, satisfacción. Benchmarking CRA. TERMINA: Diagnóstico integral y propuestas de mejora.','N° brechas identificadas vs. estándar CRA\nOportunidad del informe de diagnóstico','Jefe Planeación A&A','Diagnóstico integral del servicio A&A\nBenchmarking sectorial\nPropuestas de mejora','El diagnóstico orienta la formulación de proyectos del BEP para mejorar IANC, continuidad e IRCA.',FALSE,NULL,1),

((SELECT id FROM subprocesos WHERE codigo='SP020101'),'A020101025','Formular Plan de Optimización y Expansión Unidades Operacionales','INICIA: Diagnóstico integral del servicio y catastro de redes. INCLUYE: Priorización inversiones, formulación POIR, inscripción en BEP. TERMINA: POIR aprobado e inscrito.','% proyectos POIR inscritos en banco integrado (100%)\n% POIR ejecutado vs. programado (≥85%)','Jefe Planeación A&A','Plan POIR A&A aprobado\nProyectos inscritos en BEP','El POIR es la base del banco de proyectos de A&A: inversiones en redes, PTAP, PTAR y sistemas de captación.',FALSE,NULL,2),

((SELECT id FROM subprocesos WHERE codigo='SP020201'),'A020201027','Captar Agua Cruda','INICIA: Operación de bocatomas y canales de aducción según demanda. INCLUYE: Monitoreo caudales, operación compuertas, registro volúmenes captados. TERMINA: Agua cruda almacenada en tanques de regulación.','Eficiencia captación = Vol. captado/Vol. concesionado (≥95%)\nDisponibilidad sistema captación (≥98%)','Operador de Captación','Agua cruda captada (m³/s)\nConformidad con concesión ambiental','Eslabón 1 cadena de valor A&A: sin captación no hay producción de agua. Habilita directamente la PTAP (eslabón 2).',FALSE,NULL,3),

((SELECT id FROM subprocesos WHERE codigo='SP020201'),'A020201028','Tratar y Controlar Calidad del Agua (PTAP)','INICIA: Recepción de agua cruda en la PTAP. INCLUYE: Coagulación, floculación, sedimentación, filtración, cloración, control de calidad. TERMINA: Agua tratada lista para distribución con IRCA Sin Riesgo.','IRCA mensual (Sin Riesgo <5%)\nm³ tratados/día\nConsumo de reactivos por m³ tratado','Operador PTAP','Agua potable conforme IRCA (m³/día)\nRegistros de laboratorio PTAP','Eslabón 2 cadena de valor A&A: la producción de agua potable habilita la distribución (eslabón 3) y la comercialización (eslabón 4).',FALSE,NULL,4),

((SELECT id FROM subprocesos WHERE codigo='SP020201'),'A020201029','Suministrar Agua Potable a la Red de Distribución','INICIA: Agua potable almacenada en tanques de distribución. INCLUYE: Operación de estaciones de bombeo, control de presiones, monitoreo SCADA. TERMINA: Agua entregada a la red de distribución primaria.','Presión en red de distribución primaria (dentro de norma)\nContinuidad del suministro (%)','Operador Distribución A&A','Agua distribuida a la red primaria (m³/h)\nRegistro de presiones y caudales','Conecta la producción de agua potable (eslabón 2) con la distribución al usuario final (eslabón 3).',FALSE,NULL,5),

((SELECT id FROM subprocesos WHERE codigo='SP020204'),'A020204034','Operar Redes de Acueducto','INICIA: Monitoreo del estado de la red vía SCADA. INCLUYE: Operación válvulas, macromedidores, monitoreo presiones, atención fugas. TERMINA: Red operada y servicio continuo al usuario.','% sectores con servicio continuo (≥20h/día)\nN° fugas reportadas y atendidas en <4h','Operador Redes Acueducto','Red de distribución operada\nRegistros de presión y continuidad','Eslabón 3 cadena de valor A&A: lleva el agua potable al usuario final. Habilita la comercialización (eslabón 4).',FALSE,NULL,6),

((SELECT id FROM subprocesos WHERE codigo='SP020204'),'A020204036','Verificar Condiciones Técnicas del Sistema de Distribución','INICIA: Programación de inspecciones y mediciones en la red. INCLUYE: Medición de presiones, caudales, muestreos de calidad en red, verificación macromedidores. TERMINA: Informe de condiciones técnicas y acciones correctivas.','% puntos de red con presión dentro de norma\n% muestras de calidad conformes IRCA en red','Técnico de Redes A&A','Informe de condiciones técnicas de la red\nRegistros de presión y calidad','Habilita el control de pérdidas (IANC) y la calidad del agua en red (IRCA distribución).',FALSE,NULL,7),

((SELECT id FROM subprocesos WHERE codigo='SP020202'),'A020202063','Procesar Aguas Residuales en PTAR-C','INICIA: Llegada de aguas residuales al punto de entrada de la PTAR-C. INCLUYE: Cribado, desarenado, sedimentación primaria, reactor biológico, sedimentación secundaria. TERMINA: Efluente secundario listo para disposición final.','DBO5 efluente (mg/L) conforme PSMV\nSST efluente (mg/L) conforme norma\nEficiencia remoción DBO5 (≥80%)','Operador PTAR','Agua residual tratada (m³/día)\nConformidad PSMV (DBO5, SST, pH)','Eslabón 6 cadena de valor A&A: cierra el ciclo del agua. Habilita la disposición final conforme al PSMV.',FALSE,NULL,8),

((SELECT id FROM subprocesos WHERE codigo='SP020202'),'A020202065','Realizar Seguimiento y Control del Tratamiento AR','INICIA: Plan de monitoreo operacional y de calidad de la PTAR-C. INCLUYE: Medición de parámetros, análisis de laboratorio, ajuste de procesos. TERMINA: Informe mensual de calidad del efluente.','% parámetros PSMV conformes por muestra\nOportunidad de informes a la CVC','Jefe PTAR-C / Laboratorio','Informes de calidad del efluente\nReportes a CVC/DAACD','Habilita el cumplimiento ambiental de A&A: los datos del efluente son el respaldo técnico ante las autoridades.',FALSE,NULL,9),

((SELECT id FROM subprocesos WHERE codigo='SP020302'),'A020302044','Mantener Medidores de Agua','INICIA: Plan de mantenimiento y renovación del parque de medidores. INCLUYE: Lectura, mantenimiento, calibración y cambio de medidores defectuosos. TERMINA: Parque de medidores activo y calibrado.','% medidores activos vs. conexiones (≥95%)\nError de medición promedio (≤5%)','Técnico Medición A&A','Parque de medidores mantenido\nPlan de renovación ejecutado','Habilita la comercialización A&A y el control del IANC: sin medición precisa no hay facturación correcta ni control de pérdidas comerciales.',FALSE,NULL,10),

((SELECT id FROM subprocesos WHERE codigo='SP020303'),'A020303317','Vender Productos y Servicios A&A','INICIA: Plan de ventas y zonas de expansión. INCLUYE: Prospección de clientes, vinculación, instalación de servicio, gestión de contratos. TERMINA: Usuario vinculado, medidor instalado y primera factura emitida.','N° nuevas conexiones A&A / mes\nIngresos nuevas ventas A&A ($)','Asesor Comercial A&A','Nuevas conexiones instaladas\nContratos de prestación de servicio','Habilita el crecimiento del negocio A&A: la vinculación de nuevos usuarios aumenta los ingresos facturados (eslabón 4).',FALSE,NULL,11),

((SELECT id FROM subprocesos WHERE codigo='SP020303'),'A020303430','Gestionar Aseguramiento de Ingresos A&A','INICIA: Análisis de la cartera y balance de ingresos facturados vs. recaudados. INCLUYE: Gestión de cartera morosa, control de tarifas, recuperación de ingresos, reportes SUI. TERMINA: Informe de aseguramiento de ingresos.','Eficiencia recaudo A&A (≥92%)\nCartera vencida >90 días (≤8% cartera total)','Jefe Aseguramiento Ingresos A&A','Informe de aseguramiento de ingresos\nTarifas actualizadas en SUI','Asegura que los ingresos generados por la prestación del servicio se traduzcan efectivamente en recaudo.',FALSE,NULL,12)

ON CONFLICT (codigo) DO NOTHING;

-- MP03 – 9 actividades
INSERT INTO actividades (subproceso_id, codigo, descripcion, alcance, indicador, responsable, producto, habilitador_negocio, es_critica, nota_critica, orden) VALUES

((SELECT id FROM subprocesos WHERE codigo='SP030101'),'A030101089','Definir, Formular y Evaluar la Planeación Técnica del SDL','INICIA: Análisis de la demanda proyectada y estado de la infraestructura. INCLUYE: Plan de expansión y reposición, estudios de confiabilidad, EBIE, fichas proyectos CREG. TERMINA: Plan de Inversión SDL aprobado.','% cumplimiento Plan Inversión SDL (≥90%)\nEstudios de confiabilidad actualizados','Jefe Planeación GUENE','Plan de Inversión SDL aprobado\nEBIE actualizado\nFichas de proyectos registradas en UPME','Sin plan de inversiones del SDL no hay expansión ni reposición de la infraestructura de distribución.',FALSE,NULL,1),

((SELECT id FROM subprocesos WHERE codigo='SP030201'),'A030201093','Distribuir Energía Eléctrica','INICIA: Recibo de energía en barras de subestaciones del SDL. INCLUYE: Operación subestaciones, transformadores, redes MT y BT, monitoreo SCADA, despacho. TERMINA: Energía entregada al usuario final con SAIDI/SAIFI conformes.','SAIDI y SAIFI dentro de OM CREG\nFactor de utilización transformadores (≤80%)','Operador Centro de Control','Energía distribuida (kWh)\nSistema monitoreado y operado','Eslabón 4 cadena de valor energía (Distribución SDL): proceso central del negocio regulado. Habilita la comercialización y el alumbrado público.',FALSE,NULL,2),

((SELECT id FROM subprocesos WHERE codigo='SP030202'),'A030202102','Ejecutar el Mantenimiento del SDL','INICIA: Programación de mantenimientos preventivos y recepción de órdenes correctivas. INCLUYE: Mantenimiento redes MT/BT, subestaciones, reconectadores, transformadores. TERMINA: SDL mantenido, disponible y con certificaciones vigentes.','% mantenimientos preventivos ejecutados (≥90%)\nN° fallas post-mantenimiento (meta: 0)','Técnico de Mantenimiento SDL','SDL mantenido y disponible\nCertificaciones RETIE vigentes','El mantenimiento asegura la disponibilidad y confiabilidad del sistema, reduciendo el SAIDI y el SAIFI.',FALSE,NULL,3),

((SELECT id FROM subprocesos WHERE codigo='SP030206'),'A030206112','Desarrollar Planes de Disminución de Pérdidas','INICIA: Identificación de zonas críticas de pérdidas en el SDL. INCLUYE: Inspecciones, detección conexiones ilegales, revisión medidores, normalizaciones. TERMINA: kWh recuperados registrados y facturados.','kWh recuperados/mes vs. meta\n% reducción índice de pérdidas','Técnico Control Pérdidas Energía','kWh recuperados y facturados\nInforme de intervenciones','Cada punto de reducción en el índice de pérdidas genera ingresos adicionales para GUENE.',FALSE,NULL,4),

((SELECT id FROM subprocesos WHERE codigo='SP030204'),'A030204415','Gestionar Operación Administrativa, Financiera y Técnica AP','INICIA: Plan operativo del SALP y obligaciones del contrato con la Alcaldía. INCLUYE: Gestión técnica, administrativa, supervisión contratistas, facturación municipio, PQR. TERMINA: SALP disponible y factura mensual emitida.','Disponibilidad SALP (≥95%)\nFacturación AP oportuna','Jefe SALP','SALP operativo\nFacturación mensual al municipio','Negocio no regulado de Energía: el SALP genera ingresos complementarios para GUENE a través del contrato con la Alcaldía de Cali.',FALSE,NULL,5),

((SELECT id FROM subprocesos WHERE codigo='SP030302'),'A030302080','Realizar la Compra de Energía en el MEM','INICIA: Análisis de la demanda proyectada y precio de mercado. INCLUYE: Suscripción de contratos, operaciones en bolsa, registro ASIC/XM, gestión de coberturas. TERMINA: Contratos registrados y energía comprada dentro del presupuesto.','Costo unitario compra energía ($/kWh)\n% cumplimiento presupuesto de compra','Trader / Analista Mercado Energético','Contratos de suministro de energía\nRegistros ASIC','Eslabón 2 cadena de valor energía: la compra eficiente es la base del costo del servicio para los usuarios del mercado regulado (MR).',FALSE,NULL,6),

((SELECT id FROM subprocesos WHERE codigo='SP030303'),'A030303360','Ejecutar la Comercialización y Venta de Energía','INICIA: Plan de comercialización y base de clientes activos. INCLUYE: Facturación MR, gestión contratos MNR, prospección grandes clientes, retención. TERMINA: Contratos MNR vigentes y facturas MR emitidas.','N° clientes MNR activos vs. meta\nIngresos MNR / Total ingresos energía (%)','Asesor Comercial Energía','Contratos MNR vigentes\nFacturas MR emitidas','Eslabón 8 cadena de valor energía: genera los ingresos del negocio a partir de la distribución del SDL y la compra en el MEM.',FALSE,NULL,7),

((SELECT id FROM subprocesos WHERE codigo='SP030303'),'A030303361','Gestionar Recaudo y Aseguramiento de Ingresos Energía','INICIA: Análisis de cartera energía y balance de ingresos. INCLUYE: Gestión cartera morosa, recuperación ingresos, control tarifario, reportes XM. TERMINA: Informe de aseguramiento de ingresos energía.','Eficiencia recaudo energía (≥95%)\nCartera vencida >60 días (≤5% cartera total)','Jefe Aseguramiento Ingresos Energía','Informe aseguramiento ingresos energía\nReportes XM y SSPD actualizados','Garantiza que la energía distribuida y comercializada se traduzca efectivamente en recaudo para GUENE.',FALSE,NULL,8),

((SELECT id FROM subprocesos WHERE codigo='SP030302'),'A030302081','Gestionar Contratos de Interconexión y Uso de Infraestructura (UDI)','INICIA: Solicitud de uso de infraestructura eléctrica por terceros (operadores cable/telecom). INCLUYE: Aforos, contratos UDI, facturación, revisión proyectos de terceros. TERMINA: Contratos vigentes y facturación UDI ejecutada.','Ingresos no operacionales UDI vs. año anterior (≥+5%)\nAforos actualizados (%)','Jefe UDI GUENE','Contratos UDI vigentes\nFacturación UDI mensual','Negocio no regulado de Energía: el UDI genera ingresos complementarios aprovechando la infraestructura eléctrica existente del SDL.',FALSE,NULL,9)

ON CONFLICT (codigo) DO NOTHING;

-- MP04 – 5 actividades
INSERT INTO actividades (subproceso_id, codigo, descripcion, alcance, indicador, responsable, producto, habilitador_negocio, es_critica, nota_critica, orden) VALUES

((SELECT id FROM subprocesos WHERE codigo='SP040101'),'A040101114','Realizar Planeación Estratégica Prestación Servicios TIC','INICIA: Análisis del mercado TIC y regulación MinTIC/CRC. INCLUYE: Cuadro de mando, plan de acción, BEP TIC, proyecciones financieras, regulación. TERMINA: Plan estratégico UENTIC aprobado y comunicado.','Cumplimiento plan estratégico UENTIC (%)\n% obligaciones MinTIC cumplidas (100%)','Jefe Planeación GUENTIC','Plan estratégico UENTIC\nCuadro de mando TIC\nBEP TIC con proyecciones','El plan estratégico orienta las inversiones en red, el desarrollo de nuevos productos y la estrategia comercial por segmento.',FALSE,NULL,1),

((SELECT id FROM subprocesos WHERE codigo='SP040202'),'A040202144','Gestionar la Ejecución de Proyectos TIC','INICIA: Contrato de suministro o construcción de red TIC aprobado. INCLUYE: Supervisión de obra, control avance físico/financiero, interventoría, entrega operacional. TERMINA: Activos de red transferidos a operación.','% avance físico-financiero vs. cronograma\n% proyectos completados en plazo (≥85%)','Supervisor Proyectos TIC','Actas de seguimiento de obra\nActivos activados en SAP AM','Eslabón 3 cadena de valor TIC: la implementación de proyectos es la base del crecimiento de la infraestructura TIC para B2C, B2B y B2G.',FALSE,NULL,2),

((SELECT id FROM subprocesos WHERE codigo='SP040301'),'A040301131','Soportar y Operar los Servicios de Conectividad e Internet','INICIA: Monitoreo de la red de acceso y plataformas de internet. INCLUYE: Operación plataforma BNG/BRAS, gestión ancho de banda, resolución de incidencias. TERMINA: Servicios de internet disponibles dentro del ANS.','Disponibilidad servicio internet (≥99.5%)\nTiempo promedio resolución de incidencias (h)','Operador NOC TIC','Servicios internet disponibles (% uptime)\nTickets de incidencia resueltos','Eslabón 4 cadena de valor TIC: la operación de servicios habilita la comercialización B2C, B2B y B2G de GUENTIC.',FALSE,NULL,3),

((SELECT id FROM subprocesos WHERE codigo='SP040404'),'A040404272_B2C','Ejecutar Ventas de Servicios TIC – Segmento B2C (Hogares)','INICIA: Plan de ventas B2C y base de prospectos residenciales. INCLUYE: Prospección, visitas, propuestas, instalación y activación. TERMINA: Contrato firmado y cliente en base activa.','N° nuevos contratos B2C / mes\nChurn B2C (≤2%)','Asesor Comercial TIC B2C','Nuevos contratos B2C\nIngresos por nuevas ventas residenciales','Eslabón 6 cadena de valor TIC (segmento residencial): genera los ingresos masivos del negocio TIC aprovechando la red de fibra óptica.',FALSE,NULL,4),

((SELECT id FROM subprocesos WHERE codigo='SP040404'),'A040404272_B2B','Ejecutar Ventas de Servicios TIC – Segmento B2B/B2G (Empresas y Gobierno)','INICIA: Plan de ventas B2B/B2G y base de prospectos corporativos. INCLUYE: Prospección, propuestas técnico-comerciales, suscripción contratos, activación. TERMINA: Contratos B2B/B2G firmados y servicios activos.','N° contratos B2B/B2G activos vs. meta\nIngresos B2B/B2G / Total ingresos TIC (%)','Asesor Comercial TIC B2B/B2G','Contratos B2B/B2G vigentes\nIngresos por segmentos corporativos','Eslabón 6 cadena de valor TIC (corporativo y gobierno): los contratos B2B/B2G son los de mayor valor unitario y menor churn del negocio TIC.',FALSE,NULL,5)

ON CONFLICT (codigo) DO NOTHING;

-- MP05 – 4 actividades (+ 2 críticas)
INSERT INTO actividades (subproceso_id, codigo, descripcion, alcance, indicador, responsable, producto, habilitador_negocio, es_critica, nota_critica, orden) VALUES

((SELECT id FROM subprocesos WHERE codigo='SP050101'),'A050101001','Gestionar la Nómina y Prestaciones Sociales','INICIA: Recopilación de novedades de nómina del período. INCLUYE: Liquidación nómina, prestaciones sociales, parafiscales, descuentos por convenio. TERMINA: Nómina pagada e informes de costo laboral por negocio.','% nómina liquidada sin error (100%)\nCosto nómina por negocio correctamente imputado','Analista de Nómina','Nómina liquidada y pagada\nCosto laboral por negocio\nInformes de parafiscales','El pago oportuno asegura la disponibilidad del personal para operar GUENAA (operadores PTAP/PTAR), GUENE (técnicos SDL) y GUENTIC (NOC).',FALSE,NULL,1),

((SELECT id FROM subprocesos WHERE codigo='SP050102'),'A050102001','Documentar Conocimiento Tácito de Operadores Senior','INICIA: Identificación de los 50 cargos críticos con riesgo de jubilación en 1-3 años. INCLUYE: Entrevistas técnicas, shadowing, elaboración de manuales operativos, banco de conocimiento. TERMINA: Banco de conocimiento técnico disponible y programa de mentoring activo.','% procesos críticos documentados (≥80%)\nN° manuales operativos publicados','Jefe TH','Manuales operativos por proceso crítico\nBanco de conocimiento técnico\nPrograma de mentoring activo','⚡ URGENTE: Sin esta acción, EMCALI perderá en 5-8 años el 65% de su planta (≈1.600 funcionarios) con conocimiento tácito crítico de PTAP, PTAR, SDL y plataformas TIC.',TRUE,'ACCIÓN URGENTE: 65% de la planta supera los 50 años. Riesgo de pérdida masiva de conocimiento operativo crítico en los 3 negocios. Implementar en los primeros 6 meses.',2),

((SELECT id FROM subprocesos WHERE codigo='SP050201'),'A050201001','Gestionar Contabilidad Regulatoria por Negocio','INICIA: Creación de los centros de costo regulatorios en SAP (Mes 2-3). INCLUYE: Asignación de costos por eslabón (CC-AA-CAP, CC-AA-TRT, CC-AA-DST, CC-EN-SDL, CC-TIC-CAP, etc.), metodología ABC. TERMINA: EEFF regulatorios por negocio presentados a CRA/CREG/CRC.','% costos directos asignados a eslabón (≥95%)\nN° incumplimientos reportes regulatorios (meta: 0)','Contador Regulatorio','EEFF por negocio (CRA/CREG/CRC)\nContabilidad regulatoria activa en SAP\nCostos ABC por actividad MOP','⚡ URGENTE: Sin contabilidad regulatoria separada, EMCALI no puede defender sus tarifas ante CRA (A&A), CREG (Energía) ni CRC (TIC).',TRUE,'ACCIÓN URGENTE MES 2-3: Crear 15 centros de costo regulatorios en SAP. Implementar metodología ABC para asignación de costos compartidos. Base para defensa tarifaria ante reguladores.',3),

((SELECT id FROM subprocesos WHERE codigo='SP050301'),'A050301001','Consolidar y Ejecutar el Plan Anual de Contratación (PACC)','INICIA: Recopilación de necesidades de contratación de los 3 negocios y áreas. INCLUYE: Consolidación del PACC, priorización, cronograma de procesos, aprobación. TERMINA: PACC aprobado por la Gerencia y publicado en el SECOP.','% PACC ejecutado en fecha programada (≥85%)\nN° contratos no planificados (meta: reducción anual)','Jefe Abastecimiento','PACC consolidado y aprobado\nCronograma de procesos\nInformes de ejecución PACC','Habilita los 3 negocios: el PACC oportuno asegura reactivos para PTAP (A&A), materiales para mantenimiento SDL (Energía) y equipos para expansión de red TIC.',FALSE,NULL,4)

ON CONFLICT (codigo) DO NOTHING;

-- ── ÁREAS FUNCIONALES (por actividad) ────────────────────────
-- Insertar datos representativos para actividades críticas y principales
INSERT INTO areas_funcionales (actividad_id, nombre, responsabilidades, kpi_desempeno, kpi_productividad) VALUES
((SELECT id FROM actividades WHERE codigo='A010101003'),'Unidad de Prospectiva Estratégica Empresarial','Formular, implementar y evaluar el PEC. Coordinar CMI. Integrar banco de proyectos con proyecciones. Gestionar alianzas.','% Cumplimiento PEC (≥85%)\nCMI actualizado trimestralmente','Proyectos PEC formulados con evaluación financiera (%)'),
((SELECT id FROM actividades WHERE codigo='A020201028'),'Área Técnica PTAP','Operar las plantas de potabilización. Garantizar el IRCA Sin Riesgo. Optimizar el uso de reactivos. Gestionar los procesos de tratamiento.','IRCA mensual promedio (%)\n% eficiencia de tratamiento (m³ tratados/m³ ingresados)','m³ de agua potable producidos / turno'),
((SELECT id FROM actividades WHERE codigo='A030201093'),'Centro de Control de Energía','Operar el SDL desde el Centro de Control. Gestionar contingencias. Monitorear SAIDI y SAIFI en tiempo real. Coordinar maniobras de campo.','SAIDI y SAIFI (conforme OM CREG)\nDisponibilidad del Centro de Control (%)','kWh distribuidos por turno / N° operadores'),
((SELECT id FROM actividades WHERE codigo='A040301131'),'NOC – Centro de Operaciones de Red TIC','Monitorear y operar las plataformas TIC 24/7. Gestionar incidencias. Garantizar los ANS. Coordinar la resolución de problemas.','Disponibilidad plataformas TIC (%)\n% tickets resueltos dentro del SLA','N° incidencias resueltas / operador / turno'),
((SELECT id FROM actividades WHERE codigo='A050102001'),'Área de Gestión del Conocimiento','Gestionar el programa de gestión del conocimiento. Supervisar la documentación de procesos críticos. Administrar el banco de conocimiento técnico.','% procesos críticos documentados vs. identificados\nN° manuales operativos publicados en el año','N° procesos críticos documentados / analista / año'),
((SELECT id FROM actividades WHERE codigo='A050201001'),'Área de Contabilidad Regulatoria','Gestionar la contabilidad regulatoria de los 3 negocios. Mantener los centros de costo en SAP. Preparar los EEFF regulatorios. Aplicar la metodología ABC.','% costos críticos con trazabilidad regulatoria\nOportunidad de presentación EEFF a reguladores','N° centros de costo regulatorios activos / total requeridos');

-- ── FUNCIONARIOS PROCESO ─────────────────────────────────────
INSERT INTO funcionarios_proceso (actividad_id, funciones, kpi_desempeno, kpi_productividad) VALUES
((SELECT id FROM actividades WHERE codigo='A010101003'),'Formular el mapa estratégico. Actualizar indicadores CMI. Preparar informes de seguimiento estratégico. Coordinar con gerencias de negocio.','% metas estratégicas cumplidas en el período\nOportunidad del informe de seguimiento','N° documentos estratégicos producidos / N° planificados'),
((SELECT id FROM actividades WHERE codigo='A020201028'),'Operar procesos de tratamiento (coagulación, floculación, sedimentación, filtración, cloración). Registrar dosis de reactivos. Coordinar con laboratorio de calidad. Reportar novedades al jefe de turno.','IRCA del agua tratada\nConsumo de reactivos vs. dosis teórica','m³ de agua potable producidos / turno de trabajo'),
((SELECT id FROM actividades WHERE codigo='A030201093'),'Monitorear el SCADA del SDL en tiempo real. Ejecutar maniobras de telemando. Atender contingencias en el sistema. Registrar eventos e interrupciones. Coordinar cuadrillas de campo.','N° contingencias atendidas en <30 minutos\nDisponibilidad del SCADA (%)','kWh distribuidos sin interrupción / turno de trabajo'),
((SELECT id FROM actividades WHERE codigo='A040301131'),'Monitorear plataformas de internet y conectividad. Gestionar incidencias de nivel 1 y 2. Escalar incidencias complejas. Actualizar el dashboard de disponibilidad.','Disponibilidad servicio internet (%)\nTiempo de resolución de incidencias (h)','N° tickets cerrados / turno de trabajo'),
((SELECT id FROM actividades WHERE codigo='A050102001'),'Ejecutar entrevistas técnicas con operadores senior. Elaborar manuales operativos. Administrar el banco de conocimiento. Coordinar el programa de mentoring.','N° manuales operativos elaborados / período\nCalidad de documentación (evaluada por jefe técnico)','N° procesos documentados / analista / mes'),
((SELECT id FROM actividades WHERE codigo='A050201001'),'Registrar transacciones en los centros de costo regulatorios en SAP. Verificar la correcta asignación de costos. Preparar informes regulatorios. Coordinar con los GUENs.','% costos correctamente imputados a eslabón\n% EEFF regulatorios presentados en plazo','N° registros contables regulatorios procesados / período');
